config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :admins
  #devise_for :users
  
  #devise_for :installs
  #devise_for :admins
  namespace :admin do
    resources :shops
    resources :restaurants
    resources :masjids
    resources :images
    get '/', to: 'home#index'
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :url
	
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/masjid.rb
class Masjid < ApplicationRecord
	validates :name, presence: true
	validates :lat, presence: true
	validates :lng, presence: true
	validates :post_code, presence: true
	validates :address, presence: true
	belongs_to :pref
	has_many :images, :foreign_key => "parent_id"
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/pref.rb
class Pref < ApplicationRecord
	has_many :masjid
	has_many :restaurants
	has_many :shops
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :pref
	validates :name, presence: true
	validates :lat, presence: true
	validates :lng, presence: true
	has_many :images, :foreign_key => "parent_id"
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :pref
	has_many :images, :foreign_key => "parent_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  before_action :set_admin_shop, only: [:show, :edit, :update, :destroy]

  # GET /admin/shops
  # GET /admin/shops.json
  def index
    @admin_shops = Shop.all
  end

  # GET /admin/shops/1
  # GET /admin/shops/1.json
  def show
  end

  # GET /admin/shops/new
  def new
    @shop = Shop.new
    @pref=Pref.all
  end

  # GET /admin/shops/1/edit
  def edit
    @shop=Shop.find(params[:id])
    @pref=Pref.all
  end

  # POST /admin/shops
  # POST /admin/shops.json
  def create
    @shop = Shop.new(admin_shop_params)
    @pref=Pref.all
    
      if @shop.save
        redirect_to :controller => "admin/shops", :action => "index"
      else
        

        
      end
    
  end

  # PATCH/PUT /admin/shops/1
  # PATCH/PUT /admin/shops/1.json
  def update
    @shop = Shop.find(params[:id])
    @pref=Pref.all
      if @admin_shop.update(admin_shop_params)
        redirect_to :controller => "admin/shops", :action => "index"
      else
        format.html { render :edit }
        format.json { render json: @admin_shop.errors, status: :unprocessable_entity }
      end
    
  end

  # DELETE /admin/shops/1
  # DELETE /admin/shops/1.json
  def destroy
    @admin_shop.destroy
    respond_to do |format|
      format.html { redirect_to admin_shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_shop
      @admin_shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_shop_params
      params.require(:shop).permit(:lat, :lng, :name, :pref_id, :description, :city, :post_code, :address)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "front"
	def index
		render "index"
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/image_helper.rb
module Admin::ImageHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/admin/shops/_form.html.erb
<%= form_with(model: admin_shop, local: true) do |form| %>
  <% if admin_shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_shop.errors.count, "error") %> prohibited this admin_shop from being saved:</h2>

      <ul>
      <% admin_shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pref_id %>
    <%= form.number_field :pref_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/shops/edit.html.erb
<div class="m-portlet m-portlet--tab">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
					<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">
						Shop	
					</h3>
				</div>
			</div>
		</div>
<% if @shop.errors.any? %>
<ul>
  <% @shop.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

    <%= form_for @shop, :html=>{:class=>"m-form m-form--fit m-form--label-align-right"},url: {action: "update"} do |form| %>
	  <div class="m-portlet__body">
	  	  <div class="form-group m-form__group row">
		    <%= form.label :lat, {class: 'col-2 col-form-label'} %>
		    <div class="col-10">
		    <%= form.text_field :lat, {class: 'form-control m-input'} %>
			</div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :lng, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :lng, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :name, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :name, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :pref_id, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    	
		    	<select name="shop[pref_id]" class="form-control">
		    	<% @pref.each do |item| %>
		    	<% selected=(item.id==@shop.pref_id)? "selected" : "" %>
		    	<option value="<%= item.id %>" <%= selected %>><%= item.en %></option>
		    	<% end %>
		        </select>
		    </div>
		  </div>

		   <div class="form-group m-form__group row">
		    <%= form.label :city, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :city, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :post_code, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :post_code, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :address, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :address, {class: 'form-control m-input'} %>
			</div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :description, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_area :description, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group">
		    <%= form.submit %>
		  </div>
	   </div>
	<% end %>
</div>

app/views/admin/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Shops</h1>

<table class="table table-bordered m-table m-table--border-brand m-table--head-bg-brand">
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>Name</th>
      <th>Pref</th>
      <th>Description</th>
      <th>Images</th>
      <th ></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_shops.each do |admin_shop| %>
      <tr>
        <td><%= admin_shop.lat %></td>
        <td><%= admin_shop.lng %></td>
        <td><%= admin_shop.name %></td>
        <td><%= admin_shop.pref_id %></td>
        <td><%= admin_shop.description %></td>
        <td><%= link_to "Images",{:controller=>"admin/images",:action=>"index",:type=>"shop",:parent_id=>admin_shop.id},:class=>"btn btn-sm  btn-success" %>
            <%= admin_shop.images.where("image_type='shop'").count %>
        <td><%= link_to 'Edit', edit_admin_shop_path(admin_shop) %></td>
        <td><%= link_to "Delete",{ :controller=>"admin/shops",:action=>"destroy", :id=> admin_shop.id }, {:method => :delete,:class=>"btn btn-sm btn-danger",:data => {:confirm => 'Are you sure?'}} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Shop', new_admin_shop_path %>

app/views/admin/shops/new.html.erb
<div class="m-portlet m-portlet--tab">
		<div class="m-portlet__head">
			<div class="m-portlet__head-caption">
				<div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
					<i class="la la-gear"></i>
					</span>
					<h3 class="m-portlet__head-text">
						Shop	
					</h3>
				</div>
			</div>
		</div>
<% if @shop.errors.any? %>
<ul>
  <% @shop.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

    <%= form_for @shop, :html=>{:class=>"m-form m-form--fit m-form--label-align-right"},url: {action: "create"} do |form| %>
	  <div class="m-portlet__body">
	  	  <div class="form-group m-form__group row">
		    <%= form.label :lat, {class: 'col-2 col-form-label'} %>
		    <div class="col-10">
		    <%= form.text_field :lat, {class: 'form-control m-input'} %>
			</div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :lng, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :lng, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :name, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :name, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :pref_id, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    	
		    	<select name="shop[pref_id]" class="form-control">
		    	<% @pref.each do |item| %>
		    	<option value="<%= item.id %>"><%= item.en %></option>
		    	<% end %>
		        </select>
		    </div>
		  </div>

		   <div class="form-group m-form__group row">
		    <%= form.label :city, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :city, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :post_code, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :post_code, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :address, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_field :address, {class: 'form-control m-input'} %>
			</div>
		  </div>

		  <div class="form-group m-form__group row">
		    <%= form.label :description, {class: 'col-2 col-form-label'}  %>
		    <div class="col-10">
		    <%= form.text_area :description, {class: 'form-control m-input'} %>
		    </div>
		  </div>

		  <div class="form-group m-form__group">
		    <%= form.submit %>
		  </div>
	   </div>
	<% end %>
</div>

app/views/admin/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @admin_shop.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @admin_shop.lng %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_shop.name %>
</p>

<p>
  <strong>Pref:</strong>
  <%= @admin_shop.pref_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_shop.description %>
</p>

<%= link_to 'Edit', edit_admin_shop_path(@admin_shop) %> |
<%= link_to 'Back', admin_shops_path %>