config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :admins
  #devise_for :users
  
  #devise_for :installs
  #devise_for :admins
  namespace :admin do
    resources :shops
    resources :restaurants
    resources :masjids
    resources :images
    get '/', to: 'home#index'
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :url
	
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/masjid.rb
class Masjid < ApplicationRecord
	validates :name, presence: true
	validates :lat, presence: true
	validates :lng, presence: true
	validates :post_code, presence: true
	validates :address, presence: true
	belongs_to :pref
	has_many :images, :foreign_key => "parent_id"
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/pref.rb
class Pref < ApplicationRecord
	has_many :masjid
	has_many :restaurants
	has_many :shops
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :pref
	validates :name, presence: true
	validates :lat, presence: true
	validates :lng, presence: true
	has_many :images, :foreign_key => "parent_id"
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :pref
	has_many :images, :foreign_key => "parent_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/masjids_controller.rb
class Admin::MasjidsController < ApplicationController
  before_action :set_admin_masjid, only: [:show, :edit, :update, :destroy]

  # GET /admin/masjids
  # GET /admin/masjids.json
  def index
    @admin_masjids = Masjid.all
  end

  # GET /admin/masjids/1
  # GET /admin/masjids/1.json
  def show
  end

  # GET /admin/masjids/new
  def new
    @pref=Pref.all
    @masjid = Masjid.new
  end

  # GET /admin/masjids/1/edit
  def edit
    @pref=Pref.all
    @masjid = Masjid.find params[:id]
  end

  # POST /admin/masjids
  # POST /admin/masjids.json
  def create
    @admin_masjid = Masjid.new(admin_masjid_params)

  
      if @admin_masjid.save
        redirect_to :controller => "admin/masjids", :action => "index"
      else
        format.html { render :new }
        format.json { render json: @admin_masjid.errors, status: :unprocessable_entity }
      end
  
  end

  # PATCH/PUT /admin/masjids/1
  # PATCH/PUT /admin/masjids/1.json
  def update
    
      if @admin_masjid.update(admin_masjid_params)
        redirect_to :controller => "admin/masjids", :action => "index"
      else
        format.html { render :edit }
        format.json { render json: @admin_masjid.errors, status: :unprocessable_entity }
      end
   
  end

  # DELETE /admin/masjids/1
  # DELETE /admin/masjids/1.json
  def destroy
    @admin_masjid.destroy
    respond_to do |format|
      format.html { redirect_to admin_masjids_url, notice: 'Masjid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_masjid
      @admin_masjid = Masjid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_masjid_params
      params.require(:masjid).permit(:lat, :lng, :name, :pref_id, :description, :city, :post_code, :masjid_type, :address, :phone, :website, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "front"
	def index
		render "index"
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/image_helper.rb
module Admin::ImageHelper
end

app/helpers/admin/masjids_helper.rb
module Admin::MasjidsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/admin/masjids/_form.html.erb
<%= form_with(model: admin_masjid, local: true) do |form| %>
  <% if admin_masjid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_masjid.errors.count, "error") %> prohibited this admin_masjid from being saved:</h2>

      <ul>
      <% admin_masjid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pref_id %>
    <%= form.number_field :pref_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/masjids/edit.html.erb
<div class="m-portlet m-portlet--tab">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
						</span>
						<h3 class="m-portlet__head-text">
							Masjid	
						</h3>
					</div>
				</div>
			</div>
	<%= form_for @masjid, :html=>{:class=>"m-form m-form--fit m-form--label-align-right"},url: {action: "update"} do |form| %>
	  <div class="m-portlet__body">

	  <div class="form-group m-form__group row">
	    <%= form.label :lat, {class: 'col-2 col-form-label'} %>
	    <div class="col-10">
	    <%= form.text_field :lat, {class: 'form-control m-input'} %>
		</div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :lng, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :lng, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :name, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :name, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :pref_id, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    	
	    	<select name="masjid[pref_id]" class="form-control">
	    	<% @pref.each do |item| %>
	    	<% selected=(item.id==@masjid.pref_id)? "selected" : "" %>
	    	<option value="<%= item.id %>" <%= selected %> ><%= item.en %></option>
	    	<% end %>
	        </select>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :city, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :city, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :post_code, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :post_code, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :type, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    
	    	<% if @masjid.masjid_type==true %>
	    	<label><input type="radio" name="masjid[masjid_type]" value="1" checked>Masjid</label>
	    	<label><input type="radio" name="masjid[masjid_type]" value="0">Praying Room</label>
	    	<% else %>
	    	<label><input type="radio" name="masjid[masjid_type]" value="1">Masjid</label>
	    	<label><input type="radio" name="masjid[masjid_type]" value="0" checked >Praying Room</label>
	    	<% end %>
	    	
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :address, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :address, {class: 'form-control m-input'} %>
		</div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :phone, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :phone, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :email, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :email, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :website, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :website, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :description, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_area :description, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group">
	    <%= form.submit %>
	  </div>
		</div>
	<% end %>
</div>

app/views/admin/masjids/index.html.erb
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <h3 class="m-subheader__title ">Masjid</h3>      
     </div> 
  </div>
</div>
<!-- END: Subheader --> 
<div class="m-content">
  <p id="notice"><%= notice %></p>

  <table class="table table-bordered m-table m-table--border-brand m-table--head-bg-brand">
    <thead>
      <tr>
        <th>Lat</th>
        <th>Lng</th>
        <th>Name</th>
        <th>Pref</th>
        <th>Description</th>
        <th>Images</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @admin_masjids.each do |admin_masjid| %>
        <tr>
          <td><%= admin_masjid.lat %></td>
          <td><%= admin_masjid.lng %></td>
          <td><%= admin_masjid.name %></td>
          <td><%= admin_masjid.pref.en %></td>
          <td><%= admin_masjid.description %></td>
          <td><%= link_to "Images",{:controller=>"admin/images",:action=>"index",:type=>"masjid",:parent_id=>admin_masjid.id},:class=>"btn btn-sm  btn-success" %>
            <%= admin_masjid.images.where("image_type='masjid'").count %>
          </td>
          <td><%= link_to "Edit",{:controller=>"admin/masjids",:action=>"edit",:id=>admin_masjid.id},:class=>"btn btn-sm  btn-warning" %></td>
          <td>
            <%= link_to "Delete",{ :controller=>"admin/masjids",:action=>"destroy", :id=> admin_masjid.id }, {:method => :delete,:class=>"btn btn-sm btn-danger",:data => {:confirm => 'Are you sure?'}} %>
           
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Admin Masjid', new_admin_masjid_path %>
</div>

app/views/admin/masjids/new.html.erb
<div class="m-portlet m-portlet--tab">
			<div class="m-portlet__head">
				<div class="m-portlet__head-caption">
					<div class="m-portlet__head-title">
						<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
						</span>
						<h3 class="m-portlet__head-text">
							Masjid	
						</h3>
					</div>
				</div>
			</div>
	<%= form_for @masjid, :html=>{:class=>"m-form m-form--fit m-form--label-align-right"},url: {action: "create"} do |form| %>
	  <div class="m-portlet__body">

	  <div class="form-group m-form__group row">
	    <%= form.label :lat, {class: 'col-2 col-form-label'} %>
	    <div class="col-10">
	    <%= form.text_field :lat, {class: 'form-control m-input'} %>
		</div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :lng, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :lng, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :name, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :name, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :pref_id, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    	
	    	<select name="masjid[pref_id]" class="form-control">
	    	<% @pref.each do |item| %>
	    	<option value="<%= item.id %>"><%= item.en %></option>
	    	<% end %>
	        </select>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :city, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :city, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :post_code, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :post_code, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :type, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    	<label><input type="radio" name="masjid[masjid_type]" selected value="1">Masjid</label>
	    	<label><input type="radio" name="masjid[masjid_type]" value="0">Praying Room</label>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :address, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :address, {class: 'form-control m-input'} %>
		</div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :phone, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :phone, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :email, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :email, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :website, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_field :website, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group row">
	    <%= form.label :description, {class: 'col-2 col-form-label'}  %>
	    <div class="col-10">
	    <%= form.text_area :description, {class: 'form-control m-input'} %>
	    </div>
	  </div>

	  <div class="form-group m-form__group">
	    <%= form.submit %>
	  </div>
		</div>
	<% end %>
</div>

app/views/admin/masjids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @admin_masjid.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @admin_masjid.lng %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_masjid.name %>
</p>

<p>
  <strong>Pref:</strong>
  <%= @admin_masjid.pref_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_masjid.description %>
</p>

<%= link_to 'Edit', edit_admin_masjid_path(@admin_masjid) %> |
<%= link_to 'Back', admin_masjids_path %>