config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :admins
  #devise_for :users
  
  #devise_for :installs
  #devise_for :admins
  namespace :admin do
    resources :shops
    resources :restaurants
    resources :masjids
    resources :images
    get '/', to: 'home#index'
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :url
	
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/masjid.rb
class Masjid < ApplicationRecord
	validates :name, presence: true
	validates :lat, presence: true
	validates :lng, presence: true
	validates :post_code, presence: true
	validates :address, presence: true
	belongs_to :pref
	has_many :images, :foreign_key => "parent_id"
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/pref.rb
class Pref < ApplicationRecord
	has_many :masjid
	has_many :restaurants
	has_many :shops
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	belongs_to :pref
	validates :name, presence: true
	validates :lat, presence: true
	validates :lng, presence: true
	has_many :images, :foreign_key => "parent_id"
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :pref
	has_many :images, :foreign_key => "parent_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :set_admin_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /admin/restaurants
  # GET /admin/restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /admin/restaurants/1
  # GET /admin/restaurants/1.json
  def show
  end

  # GET /admin/restaurants/new
  def new
    @restaurant = Restaurant.new
    @country=Country.all
    @category=Category.where("category_type='restaurant'")
    @pref=Pref.all
  end

  # GET /admin/restaurants/1/edit
  def edit
    @restaurant = Restaurant.find params[:id]
    @country=Country.all
    @category=Category.where("category_type='restaurant'")
      @pref=Pref.all
  end

  # POST /admin/restaurants
  # POST /admin/restaurants.json
  def create
    @restaurant = Restaurant.new(admin_restaurant_params)

    if @restaurant.save
        redirect_to :controller => "admin/restaurants", :action => "index"
    else
      render :action => 'add'
    end
  end

  # PATCH/PUT /admin/restaurants/1
  # PATCH/PUT /admin/restaurants/1.json
  def update
    
      if @admin_restaurant.update(admin_restaurant_params)
        redirect_to :controller => "admin/restaurants", :action => "index"
      else
        format.html { render :edit }
        format.json { render json: @admin_restaurant.errors, status: :unprocessable_entity }
      end
    
  end

  # DELETE /admin/restaurants/1
  # DELETE /admin/restaurants/1.json
  def destroy
    @admin_restaurant.destroy
    respond_to do |format|
      format.html { redirect_to admin_restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_restaurant
      @admin_restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_restaurant_params
      params.require(:restaurant).permit(:lat, :lng, :name, :pref_id, :description, :kana_name, :address, :kana_address, :open, :close, :phone, :website, :status, :country_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "front"
	def index
		render "index"
	end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/image_helper.rb
module Admin::ImageHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/admin/restaurants/_form.html.erb
<%= form_with(model: @restaurant, local: true) do |form| %>
  <% if admin_restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_restaurant.errors.count, "error") %> prohibited this admin_restaurant from being saved:</h2>

      <ul>
      <% admin_restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pref_id %>
    <%= form.number_field :pref_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/restaurants/edit.html.erb
<div class="m-portlet m-portlet--tab">
      <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
          <div class="m-portlet__head-title">
            <span class="m-portlet__head-icon m--hide">
            <i class="la la-gear"></i>
            </span>
            <h3 class="m-portlet__head-text">
              Restaurant 
            </h3>
          </div>
        </div>
      </div>
      <!-- Begin Form -->
      <%= form_for @restaurant,url: {action: "update"} do |form| %>
      <div class="m-portlet__body row">
      	<div class="col-md-4">
      		<% @category.each do |row| %>
      		<p><input type="checkbox" name="category[]" value="<%= row.id %>"><%= row.category %></p>
      		<% end %> 
      	</div>
      	<div class="col-md-8">
      		
	    
	      

	      <div class="form-group m-form__group row">
	        <%= form.label :lat, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :lat, {class: 'form-control m-input'} %>
	      </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :lng, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :lng, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :name, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :name, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :kana_name, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :kana_name, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :address, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :address, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :kana_address, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :kana_address, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :open, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :open, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :close, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :close, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :pref_id, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	          <select name="restaurant[pref_id]" class="form-control">
	          <% @pref.each do |item| %>
	          <% selected=(item.id==@restaurant.pref_id)? "selected" : "" %>
	          <option value="<%= item.id %>" <%= selected %>><%= item.en %></option>
	          <% end %>
	            </select>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :phone, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :phone, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :website, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_field :website, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :status, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <select name="status" class="form-control">
	          <option value="1">Halal</option>
	          <option value="2">Halal Friendly</option>
	          <option value="3">Moving</option>
	        </select>
	        </div>
	      </div>

	      <div class="form-group m-form__group row">
	        <%= form.label :country_id, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <select name="country_idf" class="form-control" >
	          <% @country.each do |item| %>
	          <option value="<%= item.id %>"><%= item.name %></option>
	         <% end %>
	        </select>
	        </div>
	      </div>

	     <div class="form-group m-form__group row">
	        <%= form.label :description, {class: 'col-2 col-form-label'} %>
	        <div class="col-10">
	        <%= form.text_area :description, {class: 'form-control m-input'} %>
	        </div>
	      </div>

	      <div class="actions">
	        <%= form.submit %>
	      </div>
	    
	    
	   </div>
    </div>
    <% end %>
    <!-- End Form -->
</div>

app/views/admin/restaurants/index.html.erb
<!-- BEGIN: Subheader -->
<div class="m-subheader ">
  <div class="d-flex align-items-center">
    <div class="mr-auto">
      <h3 class="m-subheader__title ">Resto</h3>      
     </div> 
  </div>
</div>
<!-- END: Subheader --> 
<div class="m-content">

  <p id="notice"><%= notice %></p>


  <table class="table table-bordered m-table m-table--border-brand m-table--head-bg-brand">
    <thead>
      <tr>
        <th>Lat</th>
        <th>Lng</th>
        <th>Name</th>
        <th>Pref</th>
        <th>Description</th>
        <th>Masjid</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |admin_restaurant| %>
        <tr>
          <td><%= admin_restaurant.lat %></td>
          <td><%= admin_restaurant.lng %></td>
          <td><%= admin_restaurant.name %></td>
          <td><%= admin_restaurant.pref.en %></td>
          <td><%= admin_restaurant.description %></td>
          <td><%= link_to "Images",{:controller=>"admin/images",:action=>"index",:type=>"restaurant",:parent_id=>admin_restaurant.id},:class=>"btn btn-sm  btn-success" %>
            <%= admin_restaurant.images.where("image_type='restaurant'").count %>
          <td><%= link_to "Edit",{:controller=>"admin/restaurants",:action=>"edit",:id=>admin_restaurant.id},:class=>"btn btn-sm  btn-warning" %></td>
          <td><%= link_to "Delete",{ :controller=>"admin/restaurants",:action=>"destroy", :id=> admin_restaurant.id }, {:method => :delete,:class=>"btn btn-sm btn-danger",:data => {:confirm => 'Are you sure?'}} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Admin Restaurant', new_admin_restaurant_path %>
</div>

app/views/admin/restaurants/new.html.erb
<div class="m-portlet m-portlet--tab">
      <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
          <div class="m-portlet__head-title">
            <span class="m-portlet__head-icon m--hide">
            <i class="la la-gear"></i>
            </span>
            <h3 class="m-portlet__head-text">
              Restaurant 
            </h3>
          </div>
        </div>
      </div>
      <%= form_for @restaurant,url: {action: "create"} do |form| %>
      <div class="m-portlet__body">
        <div class="col-md-4">
          <% @category.each do |row| %>
          <p><input type="checkbox" name="category[]" value="<%= row.id %>"><%= row.category %></p>
          <% end %> 
        </div>
        <div class="col-md-8">
        
          
          <div class="form-group m-form__group row">
            <%= form.label :lat, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :lat, {class: 'form-control m-input'} %>
          </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :lng, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :lng, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :name, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :name, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :kana_name, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :kana_name, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :address, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :address, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :kana_address, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :kana_address, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :open, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :open, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :close, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :close, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :pref_id, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
              <select name="restaurant[pref_id]" class="form-control">
              <% @pref.each do |item| %>
              <option value="<%= item.id %>"><%= item.en %></option>
              <% end %>
                </select>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :phone, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :phone, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :website, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_field :website, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :status, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <select name="status" class="form-control">
              <option value="1">Halal</option>
              <option value="2">Halal Friendly</option>
              <option value="3">Moving</option>
            </select>
            </div>
          </div>

          <div class="form-group m-form__group row">
            <%= form.label :country_id, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <select name="country_idf" class="form-control" >
              <% @country.each do |item| %>
              <option value="<%= item.id %>"><%= item.name %></option>
             <% end %>
            </select>
            </div>
          </div>

         <div class="form-group m-form__group row">
            <%= form.label :description, {class: 'col-2 col-form-label'} %>
            <div class="col-10">
            <%= form.text_area :description, {class: 'form-control m-input'} %>
            </div>
          </div>

          <div class="actions">
            <%= form.submit %>
          </div>
        
        
      </div>
    </div>
    <% end %>
</div>

app/views/admin/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @admin_restaurant.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @admin_restaurant.lng %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin_restaurant.name %>
</p>

<p>
  <strong>Pref:</strong>
  <%= @admin_restaurant.pref_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_restaurant.description %>
</p>

<%= link_to 'Edit', edit_admin_restaurant_path(@admin_restaurant) %> |
<%= link_to 'Back', admin_restaurants_path %>